const KEY='joyDiary_v01',DB='joyDiaryDB',STORE='snapshots',ACTUAL='2026-07-31';
const defs=[
['day0','前日','旅は、意図から始まる','明日を迎える今の気持ちを、そのまま残しておこう。',[['intention','どんな気持ちで明日を迎えたい？','正解を探さず、今ここにある言葉を。'],['lookingForward','明日、いちばん楽しみにしていることは？','小さなことでも、ぼんやりした感覚でも大丈夫。']]],
['day1','Day 1','JOY RETREATが始まる日','今日は、どんな自分でこの時間を味わいたい？',[['intention','今日の意図',''],['heartShot','今日の心のベストショット','心が動いた瞬間を、写真ではなく言葉で残そう。'],['gratitude1','今日のありがとう 1',''],['gratitude2','今日のありがとう 2',''],['gratitude3','今日のありがとう 3',''],['tomorrow','明日への意図','']]],
['day2','Day 2','もっと、受け取る日','頑張るより、感じる。整えようとするより、味わう。',[['intention','今日の意図',''],['heartShot','今日の心のベストショット',''],['gratitude1','今日のありがとう 1',''],['gratitude2','今日のありがとう 2',''],['gratitude3','今日のありがとう 3',''],['tomorrow','明日への意図','']]],
['day3','Day 3','持ち帰るのは、感覚','終わりではなく、日常へJOYを連れて帰る日。',[['intention','今日の意図',''],['heartShot','今日の心のベストショット',''],['gratitude1','今日のありがとう 1',''],['gratitude2','今日のありがとう 2',''],['gratitude3','今日のありがとう 3',''],['carryHome','日常へ持ち帰りたい感覚','']]],
...Array.from({length:4},(_,i)=>[`day${i+4}`,`After ${i+1}`,'日常の中のJOY','旅の余韻は、日常の中で少しずつ姿を変えていく。',[['joy','今日のJOY','今日は、どんな「好き」に出会った？'],['insight','今日の気づき','リトリートを思い出して、何を感じた？'],['gratitude','今日のありがとう',''],['tomorrow','明日、楽しみなこと','']]]),
['day8','8/8','JOY味わい会','この旅で受け取ったものを、今の言葉で味わい直そう。',[['received','この旅を通して、一番受け取ったことは？',''],['favorite','これから育てたい「好き」は？',''],['changed','旅の前の自分から、何が変わった？',''],['message','旅の前の私へ、メッセージ',''],['feedback','JOY Diaryを一緒に育てるための声','好きだったところ、使いにくかったところ、あったら嬉しいこと。']]]
];
let state={testMode:true,testStart:new Date().toISOString().slice(0,10),entries:{},feedback:{},lastSavedAt:null};let dbp,timer;
const app=document.getElementById('app'),menu=document.getElementById('menu'),toggle=document.getElementById('testMode');
function openDB(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function saveSnap(data){const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE),n=Date.now();s.put({id:'latest',savedAt:n,data});s.put({id:'snapshot-'+n,savedAt:n,data});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});prune()}
async function prune(){const db=await openDB();const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE),r=s.getAll();r.onsuccess=()=>r.result.filter(x=>x.id.startsWith('snapshot-')).sort((a,b)=>b.savedAt-a.savedAt).slice(30).forEach(x=>s.delete(x.id))}
async function load(){let l=null;try{l=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}let i=null;try{const db=await openDB();i=await new Promise(res=>{const r=db.transaction(STORE).objectStore(STORE).get('latest');r.onsuccess=()=>res(r.result?.data||null);r.onerror=()=>res(null)})}catch{}const c=[l,i].filter(Boolean).sort((a,b)=>(b.lastSavedAt||0)-(a.lastSavedAt||0));if(c[0])state={...state,...c[0]};toggle.checked=state.testMode}
async function persist(){state.lastSavedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state));await saveSnap(JSON.parse(JSON.stringify(state)));document.querySelectorAll('.save').forEach(x=>x.textContent='保存済み')}catch{document.querySelectorAll('.save').forEach(x=>x.textContent='保存できませんでした')}}
function schedule(){document.querySelectorAll('.save').forEach(x=>x.textContent='保存中…');clearTimeout(timer);timer=setTimeout(persist,300)}
function d(s){const[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}function idx(){const t=d(new Date().toISOString().slice(0,10)),s=d(state.testMode?state.testStart:ACTUAL);return Math.max(0,Math.min(8,Math.floor((t-s)/86400000)))}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function phase(i){if(i===0)return'明日、JOY RETREATが始まります';if(i<=3)return`JOY RETREAT ${defs[i][1]}`;if(i<8)return`日常に還って ${i-3}日目`;return'今日はJOY味わい会の日'}
function home(){const i=idx();app.innerHTML=`<section class="hero"><div class="mark">✦</div><h1>JOY Diary</h1><p class="tag">人生は「好き」を見つける旅。</p><div class="gold"></div><div class="phase"><div class="eyebrow">${state.testMode?'TEST JOURNEY':'JOY RETREAT 2026'}</div><h2>${phase(i)}</h2><p>${defs[i][2]}</p></div><button class="primary" id="openToday">今日をひらく</button><p class="tiny">答えは、あなたの中にあります。</p></section>`;document.getElementById('openToday').onclick=()=>day(i)}
function field(dayKey,f){const[k,l,h]=f,v=state.entries?.[dayKey]?.[k]||'';return`<section class="card"><p class="prompt">${l}</p>${h?`<p class="help">${h}</p>`:''}<textarea data-day="${dayKey}" data-field="${k}" placeholder="ここに、今の言葉を…">${esc(v)}</textarea><div class="save">保存済み</div></section>`}
function day(i){const [key,label,title,sub,fields]=defs[i];app.innerHTML=`<header class="pagehead"><div class="eyebrow">${label}</div><h2>${title}</h2><p>${sub}</p></header>${fields.map(f=>field(key,f)).join('')}${state.testMode&&i<8?`<section class="card feedback"><p class="prompt">🌱 一緒に育てるメモ</p><p class="help">使っていて気づいたこと、分かりにくかったところを自由に残してね。</p><textarea data-feedback="${key}">${esc(state.feedback?.[key]||'')}</textarea><div class="save">保存済み</div></section>`:''}`;document.querySelectorAll('[data-day]').forEach(e=>e.oninput=()=>{state.entries[e.dataset.day]??={};state.entries[e.dataset.day][e.dataset.field]=e.value;schedule()});document.querySelectorAll('[data-feedback]').forEach(e=>e.oninput=()=>{state.feedback[e.dataset.feedback]=e.value;schedule()})}
function journey(){app.innerHTML=`<header class="pagehead"><div class="eyebrow">YOUR JOURNEY</div><h2>旅の記録</h2><p>その日にしか書けない言葉が、ここに積み重なっていきます。</p></header><section class="timeline">${defs.map((x,i)=>{const vals=Object.values(state.entries?.[x[0]]||{}).filter(Boolean);return`<button data-i="${i}"><div class="badge">${i||'前'}</div><div><h3>${x[1]} — ${x[2]}</h3><p>${vals.length?`${vals.length}項目を保存`:'まだ記録はありません'}</p></div></button>`}).join('')}</section>`;document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>day(+b.dataset.i))}
function backup(){const last=state.lastSavedAt?new Date(state.lastSavedAt).toLocaleString('ja-JP'):'まだ保存されていません';app.innerHTML=`<header class="pagehead"><div class="eyebrow">DATA SAFETY</div><h2>大切な言葉を守る</h2><p>端末内に二重保存し、バックアップファイルとして持ち出せます。</p></header><section class="card"><div class="statusrow"><span>ブラウザ保存</span><span class="good">自動保存</span></div><div class="statusrow"><span>端末内の履歴</span><span class="good">最大30世代</span></div><div class="statusrow"><span>最終保存</span><span>${last}</span></div></section><section class="warning">端末故障・ブラウザデータ削除・機種変更まで完全に守るには、バックアップファイルの保存が必要です。大切な記録なので、毎日1回の保存をおすすめします。</section><section class="card"><button id="export" class="primary full">バックアップを保存する</button><div style="height:10px"></div><label class="secondary full" style="display:block;text-align:center">バックアップを読み込む<input id="import" type="file" accept=".json" hidden></label></section>`;document.getElementById('export').onclick=exportData;document.getElementById('import').onchange=importData}
function exportData(){const blob=new Blob([JSON.stringify({app:'JOY Diary',version:'0.1',exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`JOY_Diary_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function importData(e){try{const p=JSON.parse(await e.target.files[0].text()),s=p.state||p;if(!s.entries)throw 0;state={...state,...s};await persist();alert('バックアップを読み込みました');home()}catch{alert('読み込めないファイルです')}}
document.getElementById('homeBtn').onclick=home;document.getElementById('menuBtn').onclick=()=>menu.showModal();document.getElementById('closeMenu').onclick=()=>menu.close();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({home,today:()=>day(idx()),journey,backup}[b.dataset.nav]()))
toggle.onchange=async()=>{state.testMode=toggle.checked;await persist();home()};document.getElementById('resetStart').onclick=async()=>{state.testMode=true;state.testStart=new Date().toISOString().slice(0,10);toggle.checked=true;await persist();alert('今日をテストの初日に設定しました');home()};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));(async()=>{await load();home()})();
